version: '3.2'
services: 
  phaser-server:
    build: ./phaser-server
    command: npm run start # run dev. ex: localhost:3000
    #command: npm run build # create build directory
    stdin_open: true
    tty: true
    volumes:
      - ./phaser-server:/opt/app
      - /opt/app/node_modules # weird line. creates an empty node_module but allows the project to work.
      # http://dchua.com/2016/02/07/getting-npm-packages-to-be-installed-with-docker-compose/
    ports:
      - "${PHASER_SERVER_PORT}:${PHASER_SERVER_PORT}" 
    env_file:
     - ./.env
